/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Lucas
 */
public class ViewGerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form ViewGerenciamento
     */
    public ViewGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCertificado = new javax.swing.JButton();
        jButtonListas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Backgroud.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLabel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(1024, 768));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento - Escola PentaSol");
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        jPanel3.setLayout(null);

        jButtonCadastrar.setBackground(new java.awt.Color(225, 174, 161));
        jButtonCadastrar.setFont(new java.awt.Font("Humanst521 Lt BT", 0, 24)); // NOI18N
        jButtonCadastrar.setForeground(new java.awt.Color(10, 33, 36));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadastrar.setBorderPainted(false);
        jButtonCadastrar.setOpaque(false);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCadastrar);
        jButtonCadastrar.setBounds(40, 660, 150, 50);
        jButtonCadastrar.getAccessibleContext().setAccessibleName("");

        jButtonCertificado.setFont(new java.awt.Font("Humanst521 Lt BT", 0, 24)); // NOI18N
        jButtonCertificado.setText("Certificado");
        jButtonCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCertificadoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCertificado);
        jButtonCertificado.setBounds(480, 660, 140, 50);

        jButtonListas.setFont(new java.awt.Font("Humanst521 Lt BT", 0, 24)); // NOI18N
        jButtonListas.setText("Listas");
        jButtonListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListasActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonListas);
        jButtonListas.setBounds(285, 660, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background02.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListasActionPerformed

    private void jButtonCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCertificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCertificadoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        new ViewCadastrar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCertificado;
    private javax.swing.JButton jButtonListas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
